import type { ClubMemberPassCardLabels } from "@/components/members/club-member-pass-card";

export function buildClubMemberPassLabels(t: {
  membersPage: {
    masterGenerateId: string;
    masterDownloadPass: string;
    masterDownloadPassBtn: string;
    clubPassMemberSince: string;
    clubPassDateOfBirth: string;
    clubPassRole: string;
    clubPassTeam: string;
    clubPassIdNo: string;
    clubPassMembership: string;
    clubPassNumber: string;
    clubPassMemberIdCard: string;
    clubPassThemeLight: string;
    clubPassThemeDark: string;
    clubPassThemeGold: string;
    clubPassDownloadFailed: string;
    clubPassModalTitle: string;
    clubPassSkillsTitle: string;
    clubPassSkillsOverview: string;
    clubPassFlipHint: string;
    clubPassFlipClubHint: string;
    clubPassFlipBackHint: string;
    clubPassOverall: string;
    clubPassOverallFull: string;
    clubPassSkillTec: string;
    clubPassSkillFit: string;
    clubPassSkillTac: string;
    clubPassSkillMnd: string;
    clubPassSkillAtt: string;
    clubPassSkillCmp: string;
    clubPassSkillTecFull: string;
    clubPassSkillFitFull: string;
    clubPassSkillTacFull: string;
    clubPassSkillMndFull: string;
    clubPassSkillAttFull: string;
    clubPassSkillCmpFull: string;
    clubPassMarketValue: string;
    clubPassMarketValueAi: string;
    clubPassMarketInfoTitle: string;
    clubPassMarketInfoBody: string;
    clubPassMarketEstimatedOn: string;
    clubPassMarketRefresh: string;
    clubPassMarketConfidenceLow: string;
    clubPassMarketConfidenceMedium: string;
    clubPassMarketConfidenceHigh: string;
    clubPassNoProgress: string;
    clubPassLevel: string;
    clubPassXp: string;
  };
  common: { close: string };
}): ClubMemberPassCardLabels & { title: string; close: string } {
  return {
    generateId: t.membersPage.masterGenerateId,
    downloadPass: t.membersPage.masterDownloadPassBtn,
    memberSince: t.membersPage.clubPassMemberSince,
    dateOfBirth: t.membersPage.clubPassDateOfBirth,
    role: t.membersPage.clubPassRole,
    team: t.membersPage.clubPassTeam,
    idNo: t.membersPage.clubPassIdNo,
    membership: t.membersPage.clubPassMembership,
    passNumber: t.membersPage.clubPassNumber,
    memberIdCard: t.membersPage.clubPassMemberIdCard,
    themeLight: t.membersPage.clubPassThemeLight,
    themeDark: t.membersPage.clubPassThemeDark,
    themeGold: t.membersPage.clubPassThemeGold,
    downloadFailed: t.membersPage.clubPassDownloadFailed,
    skillsTitle: t.membersPage.clubPassSkillsTitle,
    skillsOverview: t.membersPage.clubPassSkillsOverview,
    flipHint: t.membersPage.clubPassFlipHint,
    flipClubHint: t.membersPage.clubPassFlipClubHint,
    flipBackHint: t.membersPage.clubPassFlipBackHint,
    overall: t.membersPage.clubPassOverall,
    overallFull: t.membersPage.clubPassOverallFull,
    skillTec: t.membersPage.clubPassSkillTec,
    skillFit: t.membersPage.clubPassSkillFit,
    skillTac: t.membersPage.clubPassSkillTac,
    skillMnd: t.membersPage.clubPassSkillMnd,
    skillAtt: t.membersPage.clubPassSkillAtt,
    skillCmp: t.membersPage.clubPassSkillCmp,
    skillTecFull: t.membersPage.clubPassSkillTecFull,
    skillFitFull: t.membersPage.clubPassSkillFitFull,
    skillTacFull: t.membersPage.clubPassSkillTacFull,
    skillMndFull: t.membersPage.clubPassSkillMndFull,
    skillAttFull: t.membersPage.clubPassSkillAttFull,
    skillCmpFull: t.membersPage.clubPassSkillCmpFull,
    marketValue: t.membersPage.clubPassMarketValue,
    marketValueAi: t.membersPage.clubPassMarketValueAi,
    marketInfoTitle: t.membersPage.clubPassMarketInfoTitle,
    marketInfoBody: t.membersPage.clubPassMarketInfoBody,
    marketEstimatedOn: t.membersPage.clubPassMarketEstimatedOn,
    marketRefresh: t.membersPage.clubPassMarketRefresh,
    marketConfidenceLow: t.membersPage.clubPassMarketConfidenceLow,
    marketConfidenceMedium: t.membersPage.clubPassMarketConfidenceMedium,
    marketConfidenceHigh: t.membersPage.clubPassMarketConfidenceHigh,
    noProgress: t.membersPage.clubPassNoProgress,
    level: t.membersPage.clubPassLevel,
    xp: t.membersPage.clubPassXp,
    title: t.membersPage.clubPassModalTitle,
    close: t.common.close,
  };
}
